const MenuItems = {
  Food: {
    image: "/images/Food.png",
    items: [],
  },
  Salad: {
    items: [
      {
        id: "1",
        name: "Garden Fruit salad",
        price: "25'000",
        img: "",
        recipe: "",
      },
      {
        id: "2",
        name: "Smoked Salmon salad",
        price: "27'900",
        img: "",
        recipe: "",
      },
    ],
  },
  Pasta: {
    items: [
      {
        id: "1",
        name: "Carbonara pasta",
        price: "32'000",
        img: "",
        recipe: "",
      },
      {
        id: "2",
        name: "Bolognese pasta",
        price: "32'000",
        img: "",
        recipe: "",
      },
      {
        id: "3",
        name: "Green Garden pasta",
        price: "32'000",
        img: "",
        recipe: "",
      },
    ],
  },
  Pizza: {
    items: [
      {
        id: "21",
        name: "Hawaii pizza",
        price: "38'000",
        img: "",
        recipe: "",
      },
      {
        id: "22",
        name: "Margherita pizza",
        price: "38'000",
        img: "",
        recipe: "",
      },
      {
        id: "23",
        name: "Pepperoni pizza",
        price: "38'000",
        img: "",
        recipe: "",
      },
      {
        id: "24",
        name: "Chicken BBQ pizza",
        price: "38'000",
        img: "",
        recipe: "",
      },
      {
        id: "25",
        name: "Bolognese pizza",
        price: "38'000",
        img: "",
        recipe: "",
      },
    ],
  },

  "Cream Soup": {
    items: [
      {
        id: "21",
        name: "Broccoli cream soup",
        price: "23'900",
        img: "",
        recipe: "",
      },
      {
        id: "22",
        name: "Mushroom cream soup",
        price: "23'900",
        img: "",
        recipe: "",
      },
    ],
  },
  "": {
    items: [
      { id: "0", name: "Snack", price: "15'000", img: "", recipe: "" },
      { id: "1", name: "Fried Chicken", price: "30'000", img: "", recipe: "" },
      {
        id: "2",
        name: "Meat Collection",
        price: "129'000",
        img: "",
        recipe: "",
      },
    ],
  },
  Dessert: {
    items: [
      {
        id: "1",
        name: "Chocolate Icecream",
        price: "15'000",
        img: "",
      },
      {
        id: "2",
        name: "Oreo Icecream",
        price: "15'000",
        img: "",
      },
      {
        id: "3",
        name: "M&M Icecream",
        price: "15'000",
        img: "",
      },
      {
        id: "4",
        name: "Marshmellow Icecream",
        price: "15'000",
        img: "",
      },
    ],
  },
  Drinks: {
    image: "/images/drink.png",
    items: [],
  },
  Coffee: [
    {
      id: "1",
      name: "Americano",
      price: "9'000",
      img: "",
    },
    {
      id: "2",
      name: "Cafe Latte",
      price: "9'500",
      img: "",
    },
    {
      id: "3",
      name: "Cappucino",
      price: "9'500",
      img: "",
    },
    {
      id: "4",
      name: "Vanilla Latte",
      price: "10'000",
      img: "",
    },
    {
      id: "5",
      name: "Cafe Mocha",
      price: "10'000",
      img: "",
    },
    {
      id: "6",
      name: "Caramel Latte",
      price: "10'000",
      img: "",
    },
    { id: "7", name: "Green Tea Latte", price: "10'500", img: "" },
    { id: "8", name: "Chocolate Milk", price: "8'000", img: "" },
  ],
  Smoothie: [
    { id: "1", name: "Blueberry smoothie", price: "12'000", img: "" },
    { id: "2", name: "Strawberry smoothie", price: "12'000", img: "" },
    { id: "3", name: "Mango smoothie", price: "12'000", img: "" },
    { id: "4", name: "Kiwi smoothie", price: "12'000", img: "" },
  ],
  "Soft Drinks": [
    { id: "1", name: "Sprite", price: "9'900", img: "" },
    { id: "2", name: "Coca Cola", price: "9'900", img: "" },
    { id: "3", name: "Fanta", price: "9'900", img: "" },
    { id: "4", name: "Red Bull Original", price: "13'900", img: "" },
    { id: "5", name: "Soda Water Schweppes", price: "9'900", img: "" },
    { id: "6", name: "Tonic Water", price: "9'900", img: "" },
    { id: "7", name: "Ginger Ale", price: "9'900", img: "" },
    { id: "8", name: "Millena", price: "9'900", img: "" },
    { id: "9", name: "Millena bubble", price: "9'900", img: "" },
    { id: "10", name: "Bon Aqua Bubble Water", price: "4'500", img: "" },
  ],
  "Pot tea": [
    {
      id: "7",
      name: "Green Tea",
      price: "15'000",
      img: "",
    },
    {
      id: "8",
      name: "Fruit Tea",
      price: "15'000",
      img: "",
    },
    {
      id: "9",
      name: "Earl Grey",
      price: "15'000",
      img: "",
    },
  ],
  Juice: [
    { id: "1", name: "Apple Juice", price: "5'000", img: "" },
    { id: "2", name: "Orange Juice", price: "5'000", img: "" },
    { id: "3", name: "Multi-fruit Juice", price: "5'000", img: "" },
  ],
  Cocktails: [
    {
      id: "14",
      name: "Long Island",
      price: "34'900",
      img: "",
    },
    {
      id: "15",
      name: "Espresso Martini",
      price: "29'900",
      img: "/images/Drinks/espresso-martini.jpg",
    },
    {
      id: "16",
      name: "Mojito",
      price: "29'900",
      img: "",
    },
    {
      id: "17",
      name: "Sex On The Beach",
      price: "29'900",
      img: "/images/Drinks/Mojito.jpg",
    },
    {
      id: "18",
      name: "Fresh Jungle",
      price: "28'900",
      img: "/images/Drinks/Sex-on-the-beach.jpg",
    },
    {
      id: "19",
      name: "Strawberry Daiquiri",
      price: "28'900",
      img: "/images/Drinks/Strawberry-daiquiri.jpg",
    },
    { id: "20", name: "Bailey's Coffee", price: "25'900", img: "" },
    { id: "21", name: "Irish Coffee", price: "25'900", img: "" },
    { id: "22", name: "Pornstar Martini", price: "32'900", img: "" },
    { id: "23", name: "Aperol Spritz", price: "32'900", img: "" },
    { id: "24", name: "Pina Colada", price: "32'900", img: "" },
    { id: "25", name: "Mocktail", price: "25'900", img: "" },
    { id: "26", name: "Bartender Special", price: "39'900", img: "" },
  ],
  Beers: [
    {
      id: "10",
      name: "Heineken",
      price: "15'900",
      img: "",
    },
    {
      id: "11",
      name: "Kaltenberg",
      price: "17'900",
      img: "",
    },
    {
      id: "12",
      name: "Corona Extra",
      price: "17'900",
      img: "",
    },
    {
      id: "13",
      name: "Kirin Ichiban",
      price: "15'900",
      img: "",
    },
    {
      id: "14",
      name: "Tsingtao",
      price: "15'900",
      img: "",
    },
    {
      id: "15",
      name: "Asahi",
      price: "19'900",
      img: "",
    },
    {
      id: "16",
      name: "Asahi dry",
      price: "15'900",
      img: "",
    },
  ],
  Tequila: [
    {
      id: "14",
      name: "Sierrai tequila",
      price: "50ml 18'900",
      bottleprice: "249'900",
      img: "/images/Drinks/Sierra.jpg",
    },
    {
      id: "15",
      name: "Olmeca tequila",
      price: "50ml 22'000",
      bottleprice: "249'900",
      img: "",
    },
    {
      id: "16",
      name: "1800 tequila",
      price: "20'900",
      bottleprice: "299'900",
      img: "",
    },
  ],
  Gin: [
    {
      id: "14",
      name: "Gordon's",
      price: "17'000",
      bottleprice: "239'900",
      img: "/images/Drinks/Baileys.jpg",
    },
    {
      id: "15",
      name: "Barrister",
      price: "18'900",
      bottleprice: "239'900",
      img: "",
    },
    {
      id: "16",
      name: "Bombay Sapphire",
      price: "20'900",
      bottleprice: "259'900",
      img: "",
    },
  ],
  Liquor: [
    {
      id: "14",
      name: "Bailey's Irish Cream",
      price: "19'900",
      bottleprice: "0.7L 199'900",
      img: "/images/Drinks/Baileys.jpg",
    },
    {
      id: "15",
      name: "Jägermeister",
      price: "28'900",
      bottleprice: "0.7L 259'900",
      img: "",
    },
  ],
  Rum: [{ id: "1", name: "Captain Morgan", bottleprice: "299'900", img: "" }],
  Whiskey: [
    {
      id: "1",
      name: "Wild Turkey",
      price: "50ml 26'900",
      bottleprice: "0.7L 359'900",
      img: "",
    },
    {
      id: "2",
      name: "Jack Daniels",
      price: "50ml 25'000",
      bottleprice: "0.7L 329'900, 1L 419'900",
      img: "/images/Drinks/Jack-Daniel.jpg",
    },
    {
      id: "3",
      name: "Jack Daniels Honey",
      price: "50ml 32'900",
      bottleprice: "419'900",
      img: "",
    },
    {
      id: "4",
      name: "Ballantines",
      price: "50ml 28'900",
      bottleprice: "249'900",
      img: "/images/Drinks/Ballantines.jpg",
    },
  ],
  Vodka: [
    {
      id: "1",
      name: "Finlandia",
      price: "20'900",
      bottleprice: "269'900",
      img: "",
    },
    {
      id: "2",
      name: "Grey Goose",
      price: "35'900",
      bottleprice: "469'900",
      img: "",
    },
    { id: "3", name: "Beluga", price: "37'900", bottleprice: "479'900" },
  ],
  Wine: [
    {
      id: "1",
      name: "Domaine de La Baume",
      price: "105'000",
      img: "/images/Drinks/La-baume.jpg",
    },
    {
      id: "2",
      name: "Calvet",
      price: "105'000",
      img: "/images/Drinks/Calvet.jpg",
    },
    {
      id: "3",
      name: "Maison Castel",
      price: "95'000",
      img: "",
    },
    {
      id: "4",
      name: "Kindzmarauli",
      price: "90'000",
      img: "/images/Drinks/Kindzmarauli.jpg",
    },
    { id: "5", name: "Lous Eschenauer", price: "90'000" },
    { id: "6", name: "Hardys", price: "90'000" },
  ],
};

export default MenuItems;
